### PR TITLE
Python 3 and Windows fixes

### PR DESCRIPTION
**Pull request by raphaelm**
Hi,

these are the changes to the library I needed so far to make it work with a VeriFone H5000 on Windows using Python 3. I checked that it still works fine on Linux with Python 2. 

There are also some minor other improvements in there.

I'd love it to have this integrated into the main repo, because we are working on Python 3 and all further improvements we possibly make would stay on our fork otherwise ;)

If you want to, I'd also package this for PyPI and improve the coding style in a few places, but I didn't want to do this without asking.

Cheers
Raphael

### CODE REVIEW

**Comment by g4borg** [comment]
very nice conversion. And this is basicly running on py2.7 aswell as 3.x?
we should definitely integrate all changes.

and i think i still have to update one fixed bug in the official repo aswell.

**Comment by raphaelm** [comment]
I didn't test on 2.7 very in-depth, but everything I tested runs with 2.7 and 3.x, yes. :)

**Comment by raphaelm** [comment]
Any news here? Would be great to have this merged in the upstream repository :)

**Comment by houabdu** [comment]
Great work @raphaelm

**Review by houabdu — APPROVED** [review]

**Comment by mathiasfrey** [comment]
awesome contribution!

**Pull request merged**
